name: qris_monit_package
description: QRIS Scanner developed by Monit Tech Teams.
version: 0.0.1
homepage: https://www.monit.id/
repository: https://github.com/MonitPay/qris_monit_package
issue_tracker: https://github.com/MonitPay/qris_monit_package/issues
documentation: https://github.com/MonitPay/qris_monit_package/blob/master/README.md
publish_to: 'none'

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  qris: ^0.7.1
  mobile_scanner:
    git:
      url: https://github.com/dwikyhardi/mobile_scanner
      ref: improve


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
