name: qris_monit_package
description: QRIS Scanner developed by Monit Tech Teams.
version: 0.0.1
homepage: https://www.monit.id/
repository: https://github.com/MonitPay/qris_monit_package
issue_tracker: https://github.com/MonitPay/qris_monit_package/issues
documentation: https://github.com/MonitPay/qris_monit_package/blob/master/README.md
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  crclib: ^3.0.0
  http: ^1.1.0
  image_picker: ^1.0.4
  mobile_scanner: ^3.5.2
  qris:
    git:
      url: https://github.com/dwikyhardi/qris
      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
